Correct permissions for every view.
Hikmatillo2/ElephaHealth pull request #15
Opened 2023-07-22 07:42 UTC by MurenMurenus

2023-07-22 11:40 UTC, TheBlek requested changes

2023-07-22 11:40 UTC, TheBlek commented on ElephaHealth/chill_app/views.py
> +        data = User.objects.filter(pk=self.request.user.pk)
This could just be inlined, right?

2023-07-22 11:40 UTC, TheBlek commented on ElephaHealth/chill_app/views.py
> +class PkUserProfileDetailView(RetrieveUpdateDestroyAPIView):
I feel like PkUserProfileDetailView is not the best name here. Maybe smth like AdminUserProfileDetailView or UserbaseProfileDetailView?

2023-07-22 11:40 UTC, TheBlek commented on ElephaHealth/chill_app/views.py
> +class PkUserProfileDetailView(RetrieveUpdateDestroyAPIView):
Because the name does not convey that this gives all the users(As far as I can understand)

2023-07-23 05:40 UTC, MurenMurenus commented on ElephaHealth/chill_app/views.py
> +        data = User.objects.filter(pk=self.request.user.pk)
No, get_queryset() needs to be customized.

2023-07-23 16:13 UTC, TheBlek approved these changes

2023-07-23 16:14 UTC, merged